apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.postgres.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
