apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: reverse-proxy
  ports:
    - port: {{ .Values.reverseProxy.port }}
      targetPort: {{ .Values.reverseProxy.port }}
