apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recruiter-feedback
  namespace: recruiter-feedback
spec:
  ingressClassName: nginx
  rules:
    - host: recruiter-feedback.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reverse-proxy
                port:
                  number: 80
